### ISSUE TITLE
effettuare i test automatici di accessibilità con pa11y

### ISSUE THREAD

**Issue by dianaberna** [dianaberna/valutazione-a11y-comuni-italiani#3]
https://github.com/pa11y/pa11y

**Comment by rollamarble** [comment]
Script javascript/node che aggiunge al json che trova su https://raw.githubusercontent.com/dianaberna/valutazione-a11y-comuni-italiani/main/data/csvjson.json  i seguenti campi per ogni entry dell'array:
 - pa11y: il risultati di pa11y applicato a sito_web
 - error: la stringa di errore catturata durante l'esecuzione di pa11y 

risultato nell'output della console

```
// requirements:
//  node/npm
//  npm install sync-request
//  npm install pa11y

const pa11y = require('pa11y');
var request = require('sync-request');
async function runPa11y(body) {
 
			vaci=JSON.parse(body);
			console.log("[")
			for (let i = 0; i < vaci.length; i++) {
				 try {
					 vaci[i].pa11y = await pa11y(vaci[i].sito_web);
				} catch (error) {
					 vaci[i].error =  String(error) ; 
			         }
				console.log(JSON.stringify(vaci[i])+(i<(vaci.length-1)?",":""));
			}
		console.log("]")
 
}
	 
var res = request('GET', 'https://raw.githubusercontent.com/dianaberna/valutazione-a11y-comuni-italiani/main/data/csvjson.json');

runPa11y(res.getBody());
```

**Comment by dianaberna** [comment]
chiudo la issue perché popoliamo a mano il db visto che i vari test automatici forniscono risultati differenti
